/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    CompCadastroDeCarro: typeof import('./src/components/CompCadastroDeCarro.vue')['default']
    StructureBody: typeof import('./src/components/StructureBody.vue')['default']
  }
}
